In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np


df = pd.read_csv('/content/drive/MyDrive/tested.csv')
#df = pd.read_csv("train.csv") # SUNY CHANGED THIS
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB
None

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
413    False
414    False
415    False
416    False
417    False
Length: 418, dtype: bool

In [ ]:

df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
df['Name'][0]

'Kelly, Mr. James'

In [ ]:
print(df.isnull().mean() * 100)

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            20.574163
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.239234
Cabin          78.229665
Embarked        0.000000
dtype: float64

In [ ]:
#find  median value for Age
data = df
median_val = data['Age'].median()

data.pop('Cabin')
print("Median Value of age: ",median_val)
#replacing null value with median value
data['Age'] = data['Age'].fillna(median_val)
data.isnull().sum()

Median Value of age:  27.0

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           1
Embarked       0
dtype: int64

In [ ]:

mode_val=data['Fare'].value_counts()

data = data.fillna({"Fare": mode_val[0]})

data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
data = data.drop(['PassengerId', 'Name', 'Ticket', 'Fare'], axis=1)

In [ ]:
print(data)

     Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0           0       3    male  34.5      0      0        Q
1           1       3  female  47.0      1      0        S
2           0       2    male  62.0      0      0        Q
3           0       3    male  27.0      0      0        S
4           1       3  female  22.0      1      1        S
..        ...     ...     ...   ...    ...    ...      ...
413         0       3    male  27.0      0      0        S
414         1       1  female  39.0      0      0        C
415         0       3    male  38.5      0      0        S
416         0       3    male  27.0      0      0        S
417         0       3    male  27.0      1      1        C

[418 rows x 7 columns]

In [ ]:
data.corr()

<ipython-input-15-c44ded798807>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()

          Survived    Pclass       Age     SibSp     Parch
Survived  1.000000 -0.108615  0.008035  0.099943  0.159120
Pclass   -0.108615  1.000000 -0.467853  0.001087  0.018721
Age       0.008035 -0.467853  1.000000 -0.071197 -0.043731
SibSp     0.099943  0.001087 -0.071197  1.000000  0.306895
Parch     0.159120  0.018721 -0.043731  0.306895  1.000000

**Train and Test dataset**

In [ ]:
from sklearn.model_selection import train_test_split

NW_data = data.copy()

x = NW_data[[ 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch','Embarked']]
y = NW_data[['Survived']]

x_train_data, x_test_data, y_train_data, y_test_data = train_test_split(x, y, test_size=0.15, random_state=42)

print("x_Train dataset:", x_train_data.shape)
print("\ny_Train dataset:", y_train_data.shape)
print("\nx_Test dataset:", x_test_data.shape)
print("\ny_Test dataset:", y_test_data.shape)

x_Train dataset: (355, 6)

y_Train dataset: (355, 1)

x_Test dataset: (63, 6)

y_Test dataset: (63, 1)

**Implement Naive Bayesian Classifier**

In [ ]:
proba = {}

def count_probab():
    # Calculate probabilities for the 'Sex' column
    male_0 = NW_data[(NW_data["Sex"] == "male") & (NW_data["Survived"] == 0)].count()[0] / NW_data[NW_data["Survived"] == 0].count()[0]
    proba["male_0"] = male_0

    male_1 = NW_data[(NW_data["Sex"] == "male") & (NW_data["Survived"] == 1)].count()[0] / NW_data[NW_data["Survived"] == 1].count()[0]
    proba["male_1"] = male_1

    female_0 = NW_data[(NW_data["Sex"] == "female") & (NW_data["Survived"] == 0)].count()[0] / NW_data[NW_data["Survived"] == 0].count()[0]
    proba["female_0"] = female_0

    female_1 = NW_data[(NW_data["Sex"] == "female") & (NW_data["Survived"] == 1)].count()[0] / NW_data[NW_data["Survived"] == 1].count()[0]
    proba["female_1"] = female_1

    # Calculate probabilities for the 'Pclass' column
    pclass_1_0 = NW_data[(NW_data["Pclass"] == 1) & (NW_data["Survived"] == 0)].count()[0] / NW_data[NW_data["Survived"] == 0].count()[0]
    proba["pclass_1_0"] = pclass_1_0

    pclass_1_1 = NW_data[(NW_data["Pclass"] == 1) & (NW_data["Survived"] == 1)].count()[0] / NW_data[NW_data["Survived"] == 1].count()[0]
    proba["pclass_1_1"] = pclass_1_1

    pclass_2_0 = NW_data[(NW_data["Pclass"] == 2) & (NW_data["Survived"] == 0)].count()[0] / NW_data[NW_data["Survived"] == 0].count()[0]
    proba["pclass_2_0"] = pclass_2_0

    pclass_2_1 = NW_data[(NW_data["Pclass"] == 2) & (NW_data["Survived"] == 1)].count()[0] / NW_data[NW_data["Survived"] == 1].count()[0]
    proba["pclass_2_1"] = pclass_2_1

    pclass_3_0 = NW_data[(NW_data["Pclass"] == 3) & (NW_data["Survived"] == 0)].count()[0] / NW_data[NW_data["Survived"] == 0].count()[0]
    proba["pclass_3_0"] = pclass_3_0

    pclass_3_1 = NW_data[(NW_data["Pclass"] == 3) & (NW_data["Survived"] == 1)].count()[0] / NW_data[NW_data["Survived"] == 1].count()[0]
    proba["pclass_3_1"] = pclass_3_1

    # Calculate probabilities for the 'Age' column (assuming normal distribution)
    age_mean_not = NW_data[NW_data['Survived'] == 0]['Age'].mean()
    age_std_not = NW_data[NW_data['Survived'] == 0]['Age'].std()
    age_prob_not = 1 / (age_std_not * np.sqrt(2 * np.pi)) * np.exp(- (NW_data["Age"] - age_mean_not)**2 / (2 * age_std_not**2))
    proba["age_0"] = age_prob_not

    age_mean = NW_data[NW_data['Survived'] == 1]['Age'].mean()
    age_std = NW_data[NW_data['Survived'] == 1]['Age'].std()
    age_prob = 1 / (age_std * np.sqrt(2 * np.pi)) * np.exp(- (NW_data["Age"] - age_mean)**2 / (2 * age_std**2))
    proba["age_1"] = age_prob

    # Calculate probabilities for the 'SibSp' column
    sibsp_0_0 = NW_data[(NW_data["SibSp"] == 0) & (NW_data["Survived"] == 0)].count()[0] / NW_data[NW_data["Survived"] == 0].count()[0]
    proba["sibsp_0_0"] = sibsp_0_0

    sibsp_0_1 = NW_data[(NW_data["SibSp"] == 0) & (NW_data["Survived"] == 1)].count()[0] / NW_data[NW_data["Survived"] == 1].count()[0]
    proba["sibsp_0_1"] = sibsp_0_1

    sibsp_1_0 = NW_data[(NW_data["SibSp"] == 1) & (NW_data["Survived"] == 0)].count()[0] / NW_data[NW_data["Survived"] == 0].count()[0]
    proba["sibsp_1_0"] = sibsp_1_0

    sibsp_1_1 = NW_data[(NW_data["SibSp"] == 1) & (NW_data["Survived"] == 1)].count()[0] / NW_data[NW_data["Survived"] == 1].count()[0]
    proba["sibsp_1_1"] = sibsp_1_1

    # Calculate probabilities for the 'Parch' column
    parch_0_0 = NW_data[(NW_data["Parch"] == 0) & (NW_data["Survived"] == 0)].count()[0] / NW_data[NW_data["Survived"] == 0].count()[0]
    proba["parch_0_0"] = parch_0_0

    parch_0_1 = NW_data[(NW_data["Parch"] == 0) & (NW_data["Survived"] == 1)].count()[0] / NW_data[NW_data["Survived"] == 1].count()[0]
    proba["parch_0_1"] = parch_0_1

    parch_1_0 = NW_data[(NW_data["Parch"] == 1) & (NW_data["Survived"] == 0)].count()[0] / NW_data[NW_data["Survived"] == 0].count()[0]
    proba["parch_1_0"] = parch_1_0

    parch_1_1 = NW_data[(NW_data["Parch"] == 1) & (NW_data["Survived"] == 1)].count()[0] / NW_data[NW_data["Survived"] == 1].count()[0]
    proba["parch_1_1"] = parch_1_1


    # Calculate probabilities for the 'Embarked' column

    embarked_Q_0 = NW_data[(NW_data["Embarked"] == 'Q') & (NW_data["Survived"] == 0)].count()[0] / NW_data[NW_data["Survived"] == 0].count()[0]
    proba["embarked_Q_0"] = embarked_Q_0

    embarked_Q_1 = NW_data[(NW_data["Embarked"] == 'Q') & (NW_data["Survived"] == 1)].count()[0] / NW_data[NW_data["Survived"] == 1].count()[0]
    proba["embarked_Q_1"] = embarked_Q_1

    embarked_S_0 = NW_data[(NW_data["Embarked"] == 'S') & (NW_data["Survived"] == 0)].count()[0] / NW_data[NW_data["Survived"] == 0].count()[0]
    proba["embarked_S_0"] = embarked_S_0

    embarked_S_1 = NW_data[(NW_data["Embarked"] == 'S') & (NW_data["Survived"] == 1)].count()[0] / NW_data[NW_data["Survived"] == 1].count()[0]
    proba["embarked_S_1"] = embarked_S_1

    embarked_C_0 = NW_data[(NW_data["Embarked"] == 'C') & (NW_data["Survived"] == 0)].count()[0] / NW_data[NW_data["Survived"] == 0].count()[0]
    proba["embarked_C_0"] = embarked_C_0

    embarked_C_1 = NW_data[(NW_data["Embarked"] == 'C') & (NW_data["Survived"] == 1)].count()[0] / NW_data[NW_data["Survived"] == 1].count()[0]
    proba["embarked_C_1"] = embarked_C_1

count_probab()

In [ ]:
def naive_bayes_prediction(input_data):
     # Retrieve probabilities from the 'proba' dictionary based on user input
    sex_prob = proba[input_data['Sex'] + '_' + str(input_data['Survived'])]
    pclass_prob = proba['pclass_' + str(input_data['Pclass']) + '_' + str(input_data['Survived'])]
    age_prob = proba['age_' + str(input_data['Survived'])]
    sibsp_prob = proba['sibsp_' + str(input_data['SibSp']) + '_' + str(input_data['Survived'])]
    parch_prob = proba['parch_' + str(input_data['Parch']) + '_' + str(input_data['Survived'])]
    embarked_prob = proba['embarked_' + input_data['Embarked'] + '_' + str(input_data['Survived'])]

    # Calculate the overall probability using Naive Bayes assumption
    overall_prob = sex_prob * pclass_prob * age_prob * sibsp_prob * parch_prob * embarked_prob

    return overall_prob

# Example user input
input_data = {
    'Sex': 'female',
    'Pclass': 1,
    'Age': 30,
    'SibSp': 1,
    'Parch': 0,
    'Embarked': 'C',
    'Survived': 1
}

# Get the prediction using Naive Bayes
prediction = naive_bayes_prediction(input_data)
print("Prediction probability:", prediction)

Prediction probability: 0      0.000534
1      0.000268
2      0.000042
3      0.000554
4      0.000486
         ...
413    0.000554
414    0.000456
415    0.000466
416    0.000554
417    0.000554
Name: Age, Length: 418, dtype: float64

In [ ]:
import numpy as np
import pandas as pd

# Load the Titanic dataset
data = pd.read_csv('titanic.csv')

# Extract the features and labels from the dataset
X = data[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Embarked']].values
y = data['Survived'].values

# Convert categorical variables into numerical values
sex_mapping = {'male': 0, 'female': 1}
embarked_mapping = {'S': 0, 'C': 1, 'Q': 2}
X[:, 1] = [sex_mapping[val] for val in X[:, 1]]
X[:, 5] = [embarked_mapping[val] for val in X[:, 5]]

# Split the dataset into training and testing sets
split = int(0.8 * len(X))  # 80% for training, 20% for testing
X_train, y_train = X[:split], y[:split]
X_test, y_test = X[split:], y[split:]

class Perceptron:
    def __init__(self, num_features, learning_rate=0.1, epochs=100):
        self.num_features = num_features
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = np.random.rand(num_features + 1).astype(float)  # +1 for the bias term

    def activation(self, x):
        return 1 if x >= 0 else 0

    def predict(self, x):
        activation_input = np.dot(x, self.weights[1:]) + self.weights[0]
        return self.activation(activation_input)

    def train(self, X, y):
        for _ in range(self.epochs):
            for i in range(len(X)):
                prediction = self.predict(X[i])
                update = self.learning_rate * (y[i] - prediction)
                self.weights[1:] += update * X[i].astype(float)
                self.weights[0] += update

    def evaluate(self, X, y):
        correct_predictions = 0
        for i in range(len(X)):
            prediction = self.predict(X[i])
            if prediction == y[i]:
                correct_predictions += 1
        return correct_predictions / len(X)

# Create and train the perceptron
perceptron = Perceptron(num_features=6, learning_rate=0.1, epochs=100)

min_error = float('inf')  # Initialize minimum error with a large value
best_weights = None  # Variable to store the weights with minimum error

for epoch in range(perceptron.epochs):
    perceptron.train(X_train, y_train)
    error = 1 - perceptron.evaluate(X_train, y_train)
    print("Epoch {}: Err={:.2f}, Weights={}".format(epoch, error, perceptron.weights))

    if error < min_error:
        min_error = error
        best_weights = perceptron.weights.copy()

# Save the weight values with minimum error
np.save('perceptron_weights.npy', best_weights)

FileNotFoundError: ignored

In [ ]:
# Load the saved weights with minimum error
w = np.load('perceptron_weights.npy)

# Create a new perceptron instance with the best weights
perceptron_test = Perceptron(numb_fe=6)
perceptron_test.weights = w

# Calculate accuracy on the testing set
corr_prediction = 0
total = len(X_test)

for i in range(total):
    prediction = perceptron_test.predict(X_test[i])
    if prediction == y_test[i]:
        corr_prediction += 1

accuracy = corr_prediction / total
print("Accuracy:", accuracy)

In [ ]:
ef naive_bayes(A, B, C, D, E, F):
    # Probability of not surviving(CALCUATE Likelihood)
  gender_prob_not = (data[(data["Sex"] == A) & (data["Survived"] == 0)].count()[0]) / data[data["Survived"] == 0].count()[0]
  pclass_prob_not = (data[(data["Pclass"] == B) & (data["Survived"] == 0)].count()[0]) / data[data["Survived"] == 0].count()[0]
  sib_prob_not = (data[(data["SibSp"] == D) & (data["Survived"] == 0)].count()[0]) / data[data["Survived"] == 0].count()[0]
  parch_prob_not = (data[(data["Parch"] == E) & (data["Survived"] == 0)].count()[0]) / data[data["Survived"] == 0].count()[0]
  embarked_prob_not = (data[(data["Embarked"] == F) & (data["Survived"] == 0)].count()[0]) / data[data["Survived"] == 0].count()[0]

      # Calculate the mean and standard deviation of the age for passengers who did not survive
  age_mean_not = data[data['Survived'] == 0]['Age'].mean()
  age_std_not = data[data['Survived'] == 0]['Age'].std()

    # Calculate  the normal distribution
  age_prob_not = 1 / (age_std_not * np.sqrt(2 * np.pi)) * np.exp(- (C- age_mean_not)**2 / (2 * age_std_not**2))

    # Probability of not surviving across all passengers(prior probability)
  probability_of_total_notsurviving = data[data['Survived'] == 0].count()[0] / data.count()[0]

    # Calculate the probability of not surviving for the given parameters(posterior probability)
  prob_not = gender_prob_not * pclass_prob_not * age_prob_not * sib_prob_not * parch_prob_not * embarked_prob_not *(probability_of_total_notsurviving)


    # Probability of surviving(CALCUATE Likelihood)
  gender_prob = (data[(data["Sex"] == A) & (data["Survived"] == 1)].count()[0]) / data[data["Survived"] == 1].count()[0]
  pclass_prob = (data[(data["Pclass"] == B) & (data["Survived"] == 1)].count()[0]) / data[data["Survived"] == 1].count()[0]
  sib_prob = (data[(data["SibSp"] == D) & (data["Survived"] == 1)].count()[0]) / data[data["Survived"] == 1].count()[0]
  parch_prob = (data[(data["Parch"] == E) & (data["Survived"] == 1)].count()[0]) / data[data["Survived"] == 1].count()[0]
  embarked_prob = (data[(data["Embarked"] == F) & (data["Survived"] == 1)].count()[0]) /data[data["Survived"] == 1].count()[0]

    # Calculate the mean and standard deviation of age for passengers who survive
  age_mean = data[data['Survived'] == 1]['Age'].mean()
  age_std = data[data['Survived'] == 1]['Age'].std()
    # Calculate  normal distribution
  age_prob = 1 / (age_std * np.sqrt(2 * np.pi)) * np.exp(- (C- age_mean)**2 / (2 * age_std**2))

    # Probability of surviving across all passengers(prior probability)
  probability_of_surviving = data[data['Survived'] == 1].count()[0] / data.count()[0]

    # Calculate the probability of surviving for the given parameters(posterior probability)
  prob_survive = gender_prob * pclass_prob * age_prob * sib_prob * parch_prob * embarked_prob *(probability_of_surviving)

  if prob_survive > prob_not:
    return 1
  else:
   return 0

In [ ]:
def bayes_Gender(A):
    # Probability of not surviving given sex
    gender_prob_not = (data[(data["Sex"] == A) & (data["Survived"] == 0)].count()[0]) / data[data["Survived"] == 0].count()[0]

    # Probability of surviving given sex
    gender_prob = (data[(data["Sex"] == A) & (data["Survived"] == 1)].count()[0]) /data[data["Survived"] == 1].count()[0]

    # prior probability
    probability_of_total_notsurviving = data[data['Survived'] == 0].count()[0] / data.count()[0]

    probability_of_total_surviving = data[data['Survived'] == 1].count()[0] / data.count()[0]


    # Calculate the probability of not surviving for the given sex
    prob_not = gender_prob_not * probability_of_total_notsurviving

    # Calculate the probability of surviving for the given sex
    prob_survive = gender_prob * probability_of_total_surviving

    if prob_survive > prob_not:
        return 1
    else:
        return 0